"""Excel public blackboard sheet schema.

The system intentionally uses Excel as the only data store.
Each key business object is stored in one worksheet.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SheetSpec:
    """Definition for one public blackboard worksheet."""

    name: str
    headers: tuple[str, ...]
    required_headers: tuple[str, ...]


SHEET_SPECS: dict[str, SheetSpec] = {
    "parameter_checklist": SheetSpec(
        name="parameter_checklist",
        headers=(
            "parameter_id",
            "category",
            "name",
            "required",
            "value",
            "unit",
            "source",
            "evidence_id",
            "extraction_status",
            "confidence",
            "status",
            "owner_agent",
            "note",
            "created_by",
            "created_at",
        ),
        required_headers=("parameter_id", "name", "required", "status"),
    ),
    "project_parameters": SheetSpec(
        name="project_parameters",
        headers=(
            "parameter_id",
            "value",
            "unit",
            "source",
            "evidence_id",
            "extraction_status",
            "confidence",
            "confirmed_by",
            "updated_at",
            "created_by",
            "note",
        ),
        required_headers=("parameter_id", "value", "source", "confidence"),
    ),
    "wbs_tasks": SheetSpec(
        name="wbs_tasks",
        headers=(
            "task_id",
            "wbs_code",
            "task_name",
            "phase",
            "predecessor",
            "duration_estimate",
            "source",
            "created_by",
            "created_at",
        ),
        required_headers=("task_id", "wbs_code", "task_name", "phase"),
    ),
    "wbs_tasks_final": SheetSpec(
        name="wbs_tasks_final",
        headers=(
            "task_id",
            "wbs_code",
            "phase",
            "section",
            "floor_or_area",
            "task_name",
            "work_package",
            "quantity",
            "unit",
            "duration_days",
            "predecessor_ids",
            "relation_type",
            "lag_days",
            "source",
            "confidence",
            "note",
            "owner_agent",
        ),
        required_headers=("task_id", "wbs_code", "task_name", "duration_days"),
    ),
    "document_sections": SheetSpec(
        name="document_sections",
        headers=(
            "evidence_id",
            "document_name",
            "source_type",
            "section_title",
            "page_or_order",
            "raw_text",
            "normalized_text",
            "created_by",
            "created_at",
        ),
        required_headers=("evidence_id", "document_name", "source_type", "normalized_text"),
    ),
    "document_tables": SheetSpec(
        name="document_tables",
        headers=(
            "evidence_id",
            "document_name",
            "source_type",
            "section_title",
            "page_or_order",
            "raw_text",
            "normalized_text",
            "created_by",
            "created_at",
        ),
        required_headers=("evidence_id", "document_name", "source_type", "normalized_text"),
    ),
    "extracted_facts": SheetSpec(
        name="extracted_facts",
        headers=(
            "fact_id",
            "parameter_id",
            "name",
            "value",
            "unit",
            "status",
            "evidence_id",
            "source_priority",
            "confidence",
            "raw_text",
            "created_by",
            "created_at",
        ),
        required_headers=("fact_id", "name", "value", "status"),
    ),
    "parameter_audit": SheetSpec(
        name="parameter_audit",
        headers=(
            "audit_id",
            "parameter_id",
            "name",
            "issue_type",
            "severity",
            "status",
            "expected_value",
            "actual_value",
            "evidence_id",
            "suggestion",
            "created_by",
            "created_at",
        ),
        required_headers=("audit_id", "issue_type", "severity", "status"),
    ),
    "assumption_register": SheetSpec(
        name="assumption_register",
        headers=(
            "assumption_id",
            "target_type",
            "target_id",
            "assumption",
            "basis",
            "risk_level",
            "status",
            "created_by",
            "created_at",
        ),
        required_headers=("assumption_id", "target_type", "assumption", "status"),
    ),
    "quality_gates": SheetSpec(
        name="quality_gates",
        headers=(
            "gate_id",
            "gate_name",
            "severity",
            "result",
            "metric_value",
            "threshold",
            "message",
            "created_by",
            "created_at",
        ),
        required_headers=("gate_id", "gate_name", "severity", "result"),
    ),
    "resource_plan": SheetSpec(
        name="resource_plan",
        headers=(
            "task_id",
            "resource_type",
            "resource_name",
            "demand",
            "limit",
            "conflict_flag",
            "suggestion",
            "created_by",
            "created_at",
        ),
        required_headers=("task_id", "resource_type", "resource_name", "demand"),
    ),
    "resource_plan_final": SheetSpec(
        name="resource_plan_final",
        headers=(
            "task_id",
            "resource_type",
            "resource_name",
            "demand",
            "unit",
            "capacity",
            "period",
            "conflict_flag",
            "source",
            "confidence",
            "note",
            "owner_agent",
        ),
        required_headers=("task_id", "resource_type", "resource_name", "demand", "capacity"),
    ),
    "resource_load_daily": SheetSpec(
        name="resource_load_daily",
        headers=(
            "date_or_period",
            "resource_type",
            "resource_name",
            "demand",
            "capacity",
            "load_rate",
            "conflict_flag",
            "related_tasks",
        ),
        required_headers=("date_or_period", "resource_type", "resource_name", "demand"),
    ),
    "resource_resolution": SheetSpec(
        name="resource_resolution",
        headers=(
            "conflict_id",
            "resource_name",
            "period",
            "conflict_reason",
            "before_demand",
            "capacity",
            "measure",
            "after_demand",
            "recovered_days",
            "cost_level",
            "owner_agent",
        ),
        required_headers=("conflict_id", "resource_name", "period", "measure"),
    ),
    "schedule_initial": SheetSpec(
        name="schedule_initial",
        headers=(
            "task_id",
            "task_name",
            "phase",
            "planned_start",
            "planned_finish",
            "duration_days",
            "predecessor_ids",
            "total_float",
            "is_critical",
            "resource_summary",
            "status",
            "version",
            "generated_at",
            "generated_by",
        ),
        required_headers=("task_id", "task_name", "planned_start", "planned_finish"),
    ),
    "cpm_analysis": SheetSpec(
        name="cpm_analysis",
        headers=(
            "task_id",
            "es",
            "ef",
            "ls",
            "lf",
            "total_float",
            "free_float",
            "is_critical",
            "critical_path_no",
        ),
        required_headers=("task_id", "es", "ef", "ls", "lf", "total_float"),
    ),
    "network_edges": SheetSpec(
        name="network_edges",
        headers=(
            "edge_id",
            "from_task_id",
            "to_task_id",
            "relation_type",
            "lag_days",
            "is_critical_edge",
        ),
        required_headers=("edge_id", "from_task_id", "to_task_id", "relation_type"),
    ),
    "milestone_check": SheetSpec(
        name="milestone_check",
        headers=(
            "milestone_id",
            "milestone_name",
            "target_date",
            "actual_date",
            "result",
            "severity",
            "suggestion",
            "created_by",
            "created_at",
        ),
        required_headers=("milestone_id", "milestone_name", "actual_date", "result"),
    ),
    "debug_records": SheetSpec(
        name="debug_records",
        headers=(
            "debug_id",
            "module",
            "scenario",
            "problem",
            "severity",
            "root_cause",
            "fix_action",
            "retest_result",
            "owner",
            "status",
            "evidence_path",
        ),
        required_headers=("debug_id", "module", "scenario", "problem", "status"),
    ),
    "test_case_results": SheetSpec(
        name="test_case_results",
        headers=(
            "case_id",
            "source_case_file",
            "case_type",
            "input_summary",
            "expected_result",
            "actual_result",
            "pass_fail",
            "issue_id",
            "evidence_path",
        ),
        required_headers=("case_id", "case_type", "pass_fail"),
    ),
    "constraint_check": SheetSpec(
        name="constraint_check",
        headers=(
            "check_id",
            "target_type",
            "target_id",
            "rule_id",
            "result",
            "severity",
            "suggestion",
            "created_by",
            "created_at",
        ),
        required_headers=("check_id", "target_type", "target_id", "result", "severity"),
    ),
    "event_log": SheetSpec(
        name="event_log",
        headers=(
            "event_id",
            "event_type",
            "related_task",
            "impact_days",
            "priority",
            "status",
            "created_at",
            "created_by",
            "source",
            "confidence",
            "note",
        ),
        required_headers=("event_id", "event_type", "priority", "status"),
    ),
    "agent_message_log": SheetSpec(
        name="agent_message_log",
        headers=(
            "message_id",
            "sender",
            "receiver",
            "mode",
            "event_type",
            "priority",
            "payload_summary",
            "status",
            "timestamp",
            "related_sheet",
            "related_id",
        ),
        required_headers=("message_id", "sender", "receiver", "mode", "event_type", "status"),
    ),
    "adjustment_plan": SheetSpec(
        name="adjustment_plan",
        headers=(
            "plan_id",
            "event_id",
            "measure",
            "recovered_days",
            "cost_level",
            "risk_level",
            "score",
            "selected_flag",
            "source",
            "confidence",
            "note",
            "created_by",
            "created_at",
        ),
        required_headers=("plan_id", "event_id", "measure", "score"),
    ),
    "test_results": SheetSpec(
        name="test_results",
        headers=(
            "case_id",
            "case_name",
            "result",
            "evidence_file",
            "tester",
            "executed_at",
            "note",
        ),
        required_headers=("case_id", "case_name", "result"),
    ),
}


def get_sheet_spec(sheet_name: str) -> SheetSpec:
    """Return a sheet spec by name."""

    try:
        return SHEET_SPECS[sheet_name]
    except KeyError as exc:
        raise KeyError(f"Unknown blackboard sheet: {sheet_name}") from exc


def all_sheet_names() -> list[str]:
    """Return all required blackboard worksheet names."""

    return list(SHEET_SPECS.keys())
